version: '3.8'

services:
  # PHP + Apache service
  web:
    build: .
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  # MySQL service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pchrd_evaluation
      MYSQL_USER: pchrd_evaluation
      MYSQL_PASSWORD: pchrd_evaluation
    volumes:
      - db_data:/var/lib/mysql
  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db

volumes:
  db_data: {}
